### ISSUE TITLE
How many hours do you work daily?

### ISSUE THREAD

**Issue by matheusgontijo** [zenorocha/ama#38]
I always get myself asking how many hours big guys usually work daily. Please, consider either pet projects, Liferay, reading about IT stuff, or anything related to them.

Because it's not about how many hours people work, BUT how much people can delivery is all about.

Regards from Curitiba, Brazil dude.

**Comment by zenorocha** [comment]
Let me take last Thursday as an example. 
- 6:30am: woke up
- 7:15am: got to work
- 12:50pm - 1:15pm: lunch
- 5:15pm: got back home
- 7pm: started working on [dracula](https://github.com/zenorocha/dracula-theme/)
- 2:30am: went for sleep
- 6:30am: woke up
- ....

Of course, that's not my normal routine. In fact, I tend to not have a routine. Everything is pretty chaotic to me and I think that's because I'm driven by motivation. If there's something I want to do, I'll stop everything else and start working on it. Even if there's other things there are more important at that time. 

But that's just me. I might be just a workaholic person, so don't take this as advice.
