### ISSUE TITLE
What kinda of America Visa do you have?

### ISSUE THREAD

**Issue by matheusgontijo** [zenorocha/ama#48]
What kinda of America Visa do you have?

And please, if you would, explain to us how was to get that visa all about:
- Did you wait to much for your company to sponsor you? - if they sponsored you.
- When did you get it?
- How long is it valid until?

**Comment by rafaelstz** [comment]
+1

**Comment by zenorocha** [comment]
I did my homework before suggesting to Liferay what visa to apply.

H1B is the most obvious one, most of the people I know have it but I didn't want this one.

I was in a privileged situation since I was moving to the same company.  For that reason, I went with L1. It took several months to gather all the documents (sep-feb) but once we had it all it took about a month for USCIS to process it (feb-mar).

 There are more details related to this visa but now you have to do your homework too ;)
