### ISSUE TITLE
Selection process of good professionals

### ISSUE THREAD

**Issue by CesarNobre** [zenorocha/ama#49]
Hi Zeno, how are you?

First I would like to congratulate her work, always generating high quality content.

My question is about how to hire good people.

Surely you have been through several rigorous processes or even already applied to hire someone to his players, could comment on? Where and How to find professionals like you who are increasingly hard to find.

**Comment by zenorocha** [comment]
Hey @CesarNobre, thanks!

The thing is - there's no secret recipe.

1) You need to work really hard in order to produce high quality stuff.
2) You need to share what you've done so people can recognize your work.
3) Sorround yourself with the best professionals you know and only hire people smarter than you.

If you do that, you'll act like a magnet for good professionals.
