### ISSUE TITLE
Zeno, I know you can't preview the future, however, where are you gonna be in within 10 years?

### ISSUE THREAD

**Issue by matheusgontijo** [zenorocha/ama#66]
**First off, I completely understand there is no way to preview the future.**

Let me break it down a bit further in order to get an accurate answer.

I ask you this because many many great Software Developers down the road usually leave coding and become:
- Manager - _constantly the Enterprise field compels them to go to a higher level_
- Consultant - _using their wide experience to help other companies out_
- Company's Founder - _they figure out a fantastic idea and try to accomplish that (like Facebook, Netflix, Airbnb)_

OR are you going to be coding UNTIL the last day of your career?

I appreciate your AMA channel.

**Comment by zenorocha** [comment]
Hey @matheusgontijo, that's a very intriguing question for me. I do have short term plans that I want to accomplish but I tend not to think so much about long term plans. Anyways, I don't see myself coding until the last day of my career. Although I love being a programmer, I think there are bigger problems that be solved out there. Being a company founder is probably what I want to achieve in 10 years, but I don't think it will be a unicorn company like the ones you mentioned. It will probably be something small and probably in the programming field since I love building things for developers.

Now I need to save this link somewhere and check it again in 10 years lol

**Comment by rubens-shoji** [comment]
Hey @zenorocha, did you remember this?
